name: hitch_handler_v2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  flex_color_scheme: ^7.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  tinycolor2: ^3.0.1
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  circular_countdown_timer: ^0.2.3
  pinput: ^3.0.1
  password_strength: ^0.2.0
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  material_design_icons_flutter: ^7.0.7296
  flutter_typeahead: ^4.8.0
  material_symbols_icons: ^4.2668.0
  intl_phone_field: ^3.2.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  gap: ^3.0.1
  expandable_text: ^2.3.0
  timeago: ^3.6.0
  like_button: ^2.0.5
  flutter_zoom_drawer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/illustrations/
